name: Docker Image Build

on:
  push:
    branches: [ "main" ]   
  pull_request:
    branches: [ "main" ]   

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build Docker Compose
        run: |
          cd dockercompose
          docker-compose build
